#Clean dataframe
import pandas as pd
import re

# this is a comment 
# 

'''
THis is also a comment
'''

"""
This a comment
"""
# class for cleaning the data and ensuring that the data is usable

class TweetCleanser:
    '''
    - this class will ensure we clean the data and that the data is 
    in a format that is usable. 
    Ensuring that our data is easy is work with
    '''
    def __init__(self, df:pd.DataFrame):
        self.df = df
        print("Automation in Action....!!!")

    def drop_unwanted_columns(self, df:pd.DataFrame)->pd.DataFrame:
        '''
        This function will remove the rows that have column names. 
        This is an error generated by collecting the data
        '''
        unwanted_rows = self.df[self.df['retweet_count'] == 'retweet_count'].index
        self.df.drop(unwanted_rows, inplace=True)
        self.df = self.df[self.df['polarity'] != 'polarity']
        return self.df
    
    # drop duplicates
    def drop_duplicates(self, df:pd.DataFrame)->pd.DataFrame:
        '''
        the fuction to drop for me hthe duplicates in my data
        '''
        self.df = self.df.drop_duplicates(subset=['original_text'])
        return self.df
    
    # convert the time to datatime format
    def convert_to_datetime(self, df:pd.DataFrame)->pd.DataFrame:
        '''
        Convert to datetime
        '''

if __name__ == "__main__":
    df = pd.read_json('C:/Users/Admin/Desktop/Desmondonam/Data_Science/twitter_analysis/Data/Economic_Twitter_Data_minified.json')
    cleanser = TweetCleanser(df)
    cleanser.drop_unwanted_columns(df)
    cleanser.drop_duplicates(df)

